- name: Install x86 things
  hosts: os-builder-targets
  tags: x86

  tasks:
    - name: Install boot packages for Arch
      community.general.pacman:
        package:
          - linux
          - grub
          - memtest86+-efi
          - amd-ucode
          - intel-ucode
          - linux-firmware
        state: present
      when: ansible_facts['pkg_mgr'] == "pacman"
      tags: install, kernel, grub

    - name: Install boot packages for Debian
      ansible.builtin.apt:
        package:
          - linux-image-amd64
          - grub-efi-amd64
          - memtest86+
          - amd64-microcode
          - intel-microcode
          - firmware-linux
        state: present
      when: ansible_facts['pkg_mgr'] == "apt"
      tags: install, kernel, grub

    - name: Kernel cmdline
      ansible.builtin.lineinfile:
        dest: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT'
        line: 'GRUB_CMDLINE_LINUX_DEFAULT="loglevel=9 audit=0 console=tty0"'
